version: '3.9'

services:
  keycloak:
    build:
      context: ..
      dockerfile: docker_pro/keycloak.Dockerfile
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - "8099:8080"
    depends_on:
      - db
    networks:
      - keycloak-network

  db:
    build:
      context: ..
      dockerfile: docker_pro/postgres.Dockerfile
    container_name: postgres_container
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    networks:
      - keycloak-network
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ..
      dockerfile: docker_pro/nginx.Dockerfile
    container_name: nginx_container
    ports:
      # Port FastAPI
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  db_data: